name: Deployment Pipeline

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run lint
      - name: Build the user interface
        run: npm run build:ui
      - name: e2e tests
        uses: cypress-io/github-action@0ee1130f05f69098ab5c560bd198fecf5a14d75b
        with:
          command: npm run test:e2e
          start: npm run test-mode
          wait-on: http://localhost:3001
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '#skip')
    needs: [lint-and-test]
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '22'
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: npm install
      - run: npm run build:ui
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: CI/CD New Version Deployed
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
             "content": "**✅ Deploy Succeeded!**\n🔢 Version: '${{ github.sha }}'"
          }' \
          ${{ secrets.DISCORD_WEBHOOK }}
      - name: CI/CD Deployment Failed
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
           "content": "**❌ Deploy Failed!**\n🔍 Logs: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'"
          }' \
          ${{ secrets.DISCORD_WEBHOOK }}
  tag_release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '#skip')
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
